import { ILogger } from "@spt/models/spt/utils/ILogger";
import { DatabaseServer } from "@spt/servers/DatabaseServer";
import { HashUtil } from "@spt/utils/HashUtil";
import { LeavesUtils } from "./LeavesUtils";
import { PreSptModLoader } from "@spt/loaders/PreSptModLoader";
export declare class LeavesSettingsManager {
    protected preSptModLoader: PreSptModLoader;
    protected databaseServer: DatabaseServer;
    protected hashUtil: HashUtil;
    protected logger: ILogger;
    protected leavesUtils: LeavesUtils;
    private config;
    private weaponCategories;
    private handoverCategories;
    private weaponCategoriesWeighting;
    private gearList;
    private localizationChanges;
    private bodyParts;
    private validTargets;
    private validMaps;
    private easyMaps;
    private locationIDMap;
    private questWhiteList;
    private rewardTable;
    constructor(preSptModLoader: PreSptModLoader, databaseServer: DatabaseServer, hashUtil: HashUtil, logger: ILogger, leavesUtils: LeavesUtils);
    private loadQuestWhitelists;
    getQuestWhitelist(): string[];
    getRewardsTable(): any;
    private loadWeaponCategories;
    private loadHandoverCategories;
    getLocalizationChangesToSave(): any;
    setLocalzationChangesToSave(localizationChanges: any): void;
    getGearList(): any;
    getEasyMaps(): string[];
    getBodyParts(): string[];
    getBodypartSelection(count: number): string[];
    getValidTargets(): string[];
    getValidMaps(): string[];
    getLocationIDMap(): any;
    getweaponCategoriesWeighting(): any;
    getWeaponCategories(): any;
    gethandoverCategories(): any;
    getConfig(): any;
}
